### PR TITLE
feat: Add buttons to decrease and increase volume, clear the entire song queue, shuffle the song queue, and more. (REOPEN)

### PR DESCRIPTION
**Pull request by NekoSakuraLucia**
### Log of changes for each file:

- Add buttons for decreasing and increasing volume
- Add buttons to clear and shuffle the song queue
- Fix index.js to include handling for additional button interactions

The source has been changed to ytsearch because Lavalink can now play music from YouTube if certain plugins are installed. I installed them, and it works.

### CODE REVIEW

**Comment by NekoSakuraLucia** [comment]
Alright, bro, now hurry up and merge the code. I'm afraid it'll conflict again, haha!

**Comment by Obskurath** [comment]
LGTM

**Comment by Obskurath** [comment]
What plugin did you install on lavalink to add it to mine or send me your application.yml

**Comment by NekoSakuraLucia** [comment]
> What plugin did you install on lavalink to add it to mine or send me your application.yml

I've installed these plugins:

```css
youtube-plugin, lavalyrics-plugin, lavasrc-plugin, lavasearch-plugin, nekomoew-music-plugins.
```

As for the nekomoew-music-plugins, it's the one I made myself. It’s unrelated to the others. I created it to support playback from Bilibili only.

**Comment by Obskurath** [comment]
Okay

**Comment by NekoSakuraLucia** [comment]
> Okay

Or you can use someone else's that is available for free on this website: [lavalink hosting](https://lavalink.darrennathanael.com/)

**Comment by Obskurath** [comment]
Im checking it

**Comment by Obskurath** [comment]
I will just use one of the free ones, its easier, thanks

**Comment by NekoSakuraLucia** [comment]
> I will just use one of the free ones, its easier, thanks

Did you choose the free lavalink that can play ytsearch?

**Comment by Obskurath** [comment]
The one with a lot of plugins, it works perfectly

**Pull request merged**
