### PR TITLE
new: Added the filters, seek, and volume commands, adjusted the code, and added comments in the Events Manager section.

### PR DESCRIPTION
**Pull request by NekoSakuraLucia**
#### In this update, new commands have been added: the filters command to manage song filters, the volume command to adjust the song's volume, and the seek command to fast-forward the song to a specific time. Additionally, comments have been added to the Events Manager.

### CODE REVIEW

**Comment by NekoSakuraLucia** [comment]
When are you going to check the changes and merge my code into your repo? I've been waiting for a long time.

**Comment by Obskurath** [comment]
> When are you going to check the changes and merge my code into your repo? I've been waiting for a long time.

Different time zones im checking it rn

**Comment by Obskurath** [comment]
Actually the last time i didnt slept untill 8am doing this hahaha

**Comment by NekoSakuraLucia** [comment]
> > When are you going to check the changes and merge my code into your repo? I've been waiting for a long time.
> 
> Different time zones im checking it rn

That's true, I totally forgot haha. I ended up sleeping and almost woke up twice already. I completely forgot that the time zones are different haha.

**Comment by Obskurath** [comment]
Yep, and i was at the gym

**Comment by NekoSakuraLucia** [comment]
> Yep, and i was at the gym

Wow, are you working out right now?

**Comment by Obskurath** [comment]
I was,  like 3-4 hours of workout

**Comment by NekoSakuraLucia** [comment]
The `pause.js` and `resume.js` commands should be organized by their type. It is not recommended to use `player.pause(true)` or `player.pause(false)` because some people might get confused.

The types should be as follows:
```ts
    /**
     * Pause the player
     */
    async pause() {
        if (this.paused && !this.playing) throw new Error("Player is already paused - not able to pause.");
        this.paused = true;
        this.lastPositionChange = null; // needs to removed to not cause issues
        const now = performance.now();
        await this.node.updatePlayer({ guildId: this.guildId, playerOptions: { paused: true } });
        this.ping.lavalink = Math.round((performance.now() - now) / 10) / 100;
        return this;
    }

    /**
     * Resume the Player
     */
    async resume() {
        if (!this.paused) throw new Error("Player isn't paused - not able to resume.");
        this.paused = false;
        const now = performance.now();
        await this.node.updatePlayer({ guildId: this.guildId, playerOptions: { paused: false } });
        this.ping.lavalink = Math.round((performance.now() - now) / 10) / 100;
        return this;
    }
```

**Comment by Obskurath** [comment]
Okay, implementing them on the code

**Pull request merged**
