### PR TITLE
feat: Add buttons to decrease and increase volume, clear the entire song queue, shuffle the song queue, and more.

### PR DESCRIPTION
**Pull request by NekoSakuraLucia**
## Log of changes for each file:

- Add buttons for decreasing and increasing volume
- Add buttons to clear and shuffle the song queue
- Fix index.js to include handling for additional button interactions

**Please do not merge: The code or features have not been fully added yet. If you click in, please read this first. Once I have finished adding the code or features, I will let you know when it is ready to merge. Thank you!**

### CODE REVIEW

**Comment by NekoSakuraLucia** [comment]
image

Huh? How could this be contradictory? I'm confused right now.

**Comment by Obskurath** [comment]
I changed the path for commands 

Grouped commands by type (music and general) 

Also created folder for config

**Comment by Obskurath** [comment]
Screenshot 2024-11-27 153641

**Comment by NekoSakuraLucia** [comment]
Whoa, I have to fix a lot of things here. Well, never mind. I'll give it a try, but I’m not sure if it’s going to cause even more conflicts than before, haha.

**Comment by NekoSakuraLucia** [comment]
### Let me close the PR for now. I need to make some corrections first, and then I'll reopen it later.

**Pull request closed without merging**
