### PR TITLE
feat: Add some features and reorganize the code

### PR DESCRIPTION
**Pull request by NekoSakuraLucia**
In this fix, the usage of `await` in `createNowPlaying` has been modified, and the code in other files has been reorganized. Additionally, the embed for the `leave`, `seek`, `loop` and `volume` commands has been added, and the embed for other commands will be improved if needed for better appearance.

### CODE REVIEW

**Comment by Obskurath** [comment]
Okay, I'm still doing embeds for /leave and skip, but I'm thinking about how should I do the embed for skip, I like the play embed, I'm planning on doing something similar

**Comment by NekoSakuraLucia** [comment]
> Okay, I'm still doing embeds for /leave and skip, but I'm thinking about how should I do the embed for skip, I like the play embed, I'm planning on doing something similar

If I may suggest, for the play command in the canvas section, you should implement caching because generating the image takes time, which will make Discord wait for the command. And if it takes too long, it could result in an interaction timeout, which could cause an error.

**Comment by Obskurath** [comment]
At the moment no timeout has occurred to me, I didn't thought about that, I just made it pretty 

I will do that

**Comment by Obskurath** [comment]
At the moment no timeout has occurred to me, I didn't thought about that, I just made it pretty 

I will do that 

But actually the song starts before rendering the image 

I was thinking that maybe if I send a Reply saying 
"Now playing song" 

To give time to generate the image and when it's ready, to send de Embed with the image and play the music

Maybe that's a good solution, what do you think?

**Comment by NekoSakuraLucia** [comment]
An interaction timeout will occur at each moment, and we cannot predict it. It might even happen at Discord's API.

---

Yes, sending a 'Now playing song' message seems like a good way to give time for the image to generate. Once the image is ready, you can send the Embed with the image and play the music. That should improve the user experience

**Comment by NekoSakuraLucia** [comment]
If you can't do the cache of the canvas in this part, bring it to me to do because I can do it.

**Comment by NekoSakuraLucia** [comment]
Okay, bro, you can merge the code now. I've added everything, and right now I have no idea what to do next, haha.

**Comment by Obskurath** [comment]
I made some changes, based on the events on Player.js.
Optimized embed flow in Player.js

- Made the play embed appear with each song that is played.
- To prevent embeds from previous songs from affecting the new ones, 
  the play embed is now deleted when the song ends or the queue ends.

**Comment by Obskurath** [comment]
But one thing that im seeing is that the paths are becomming a hassle, we should change to ts and just start changin to absolute paths.
But. i have no idea how to change to ts and its possible if the project doesnt have src folder?
@NekoSakuraLucia

**Comment by NekoSakuraLucia** [comment]
> But one thing that im seeing is that the paths are becomming a hassle, we should change to ts and just start changin to absolute paths. But. i have no idea how to change to ts and its possible if the project doesnt have src folder? @NekoSakuraLucia

You can definitely switch to TypeScript even if the project doesn’t have a src folder. The src folder is just a convention for organizing the source code, but it’s not required for TypeScript to work. You can set up TypeScript in any folder structure you prefer.
@Obskurath

**Comment by NekoSakuraLucia** [comment]
> > But one thing that im seeing is that the paths are becomming a hassle, we should change to ts and just start changin to absolute paths. But. i have no idea how to change to ts and its possible if the project doesnt have src folder? @NekoSakuraLucia
> 
> You can definitely switch to TypeScript even if the project doesn’t have a src folder. The src folder is just a convention for organizing the source code, but it’s not required for TypeScript to work. You can set up TypeScript in any folder structure you prefer. @Obskurath

```ts
{
  "compilerOptions": {
    "target": "ES2020",           // Choose the JavaScript version to compile to
    "module": "CommonJS",         // Select the module system to use in Node.js
    "outDir": "./dist",           // Directory to output the compiled .ts files
    "rootDir": ".",               // Set the root directory to the project root (no need for 'src')
    "baseUrl": ".",               // Set the baseUrl to the project root
    "paths": {
      "@/*": ["*"]                // Enable the use of absolute paths
    },
    "esModuleInterop": true,      // Enable compatibility for ES modules
    "skipLibCheck": true,         // Skip type checking of declaration files
    "strict": true                // Enable strict type checking
  },
  "include": [
    "*.ts"                        // Include .ts files located in the root directory
  ],
  "exclude": [
    "node_modules"                // Exclude the 'node_modules' directory
  ]
}
```

**Comment by NekoSakuraLucia** [comment]
I might work on fixing the code and enhancing the log presentation around 1 PM Thailand time. There might be a PR opened as well.

**Pull request merged**
