### PR TITLE
feat: Refactored the entire code by removing all the libs used for downloading music and replacing them with Lavalink for music playback.

### PR DESCRIPTION
**Pull request by NekoSakuraLucia**
#### How to install and use
```js
// Set up the Lavalink node before using it.
client.lavalink = new LavalinkManager({
    nodes: [
        {
            authorization: "youshallnotpass",
            host: "localhost",
            port: 2333,
            id: "Soundhub",
        }
    ],
    sendToShard: (guildId, payload) => client.guilds.cache.get(guildId)?.shard?.send(payload),
    autoSkip: true,
    client: {
        id: process.env.CLIENT_ID,
        username: "Soundhub", 
    },
});
```

#### To connect to Lavalink, only Lavalink with version v4.0.0 or higher is required.
---
#### As for other commands or Events Manager, we will continue to add them. Please be patient.

### CODE REVIEW

**Comment by Obskurath** [comment]
Im gonna check the changes

**Comment by NekoSakuraLucia** [comment]
Okay!

**Comment by Obskurath** [comment]
By any chance did you install some plugin on lavalink?

**Comment by NekoSakuraLucia** [comment]
> By any chance did you install some plugin on lavalink?

Does this refer to the LavaLink launcher? If the LavaLink launcher hasn't installed anything at all.

But if it's my music bot, it has plugins for Spotify and Bilibili that I wrote myself (but if the one you're referring to hasn't installed anything at all)."

**Comment by Obskurath** [comment]
Nope just ytsearch giving problems, even i fi enabled it on application.yml, so i just changed to soundclub

**Comment by NekoSakuraLucia** [comment]
> Nope just ytsearch giving problems, even i fi enabled it on application.yml, so i just changed to soundclub

Soundclub? Oh, you mean Soundcloud, right? You need to set it to `scsearch` It can't play via `ytsearch` right now because I'm running Lavalink on my own machine, and it's not working. So, I have to use someone else's server to make it work.

I still need to find the additional plugin for it. I don't know either

**Comment by Obskurath** [comment]
Yeah soundcloud hahaha
Im gonna try to fix it with ytsearch or maybe add a subcommand on play.js that lets you select the source

**Comment by NekoSakuraLucia** [comment]
I'll add the seek command, autoplay, and filters soon, along with many other interesting features. Just wait until I get home first.

**Comment by Obskurath** [comment]
Okay, i will be doing the embeds for the commands

**Pull request merged**
